### ISSUE TITLE
同学可以留个邮箱吗  复旦PCserver群有人要找你开发合作呢~

### ISSUE THREAD

**Issue by kuangxiaoye** [zhongyuchen/bus-schedule#23]

**Comment by zhongyuchen** [comment]
> No description provided.

@kuangxiaoye zhongyu_chen@qq.com

**Comment by zhongyuchen** [comment]
> No description provided.

你可以留个联系方式，我把email发给你～

**Comment by zhongyuchen** [comment]
> No description provided.

@kuangxiaoye 你可以留个联系方式，我把email发给你～
